project:
  output-dir: _output
  render:
    - "*.qmd"
    - "!shinylive_assets/"

  resources:
    - index.html

  
  
format:
  html: 
    grid:
      sidebar-width: 10px
      body-width: 1900px
      margin-width: 10px
      gutter-width: 1.5rem